[project]
name = "sphinx-users-jp"
version = "0"
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
    "setuptools>=75.3.0",
    "sphinx>=8.1.3",
    "pillow>=11.0.0",
    "sphinxext-opengraph>=0.9.1",
    "sphinxcontrib-gist>=0.1.0",
    "sphinxcontrib-trimblank>=1.0.3",
]
